Feature/add my ip tool
kesko-dev/kai-deploy-tool pull request #28
Opened 2020-11-03 14:29 UTC by latvanii

2020-11-03 15:21 UTC, PolarPayne requested changes
Lots of small notes and a single one which is a bit larger, overall this looks very good. 👍

Personally I would have made the API look a bit different. Making it so that running with `kai addmyip --list` would just list all of the IPs added with the tool, and running with `kai addmyip --cleanup` would cleanup all of the IPs added with the tool, and without either of them it would add your IP to the whitelist.

2020-11-03 15:21 UTC, PolarPayne commented on kai/cli/addmyip.py
> +    return result.json()['ip']
I guess this works, but it feels _hack-ish_... Although I can't find a better reliable way to do this (that would e.g. also work on WSL). 🤔

2020-11-03 15:21 UTC, PolarPayne commented on kai/cli/addmyip.py
> +    add_my_ip(vars(args))
Or return `add_my_ip` and just use the `argparse.Namespace` straight in that.

2020-11-03 15:21 UTC, PolarPayne commented on kai/cli/addmyip.py
> +            remove_ip_ranges_added_by_tool(security_group_id)
I would probably make the default behavior work the other way around, because now if multiple people are using this tool they will remove each others IPs.

The other option is to also list the whitelist IPs and interactively ask from the user whether they want to remove them. This could show a prompt like the following, preferably of course only showing it only once during a single run.
```
The following IPs have been added by this tool previously:
1) 1.2.3.4/32 Added by PayneCarbon at UTC time: 2020-11-03 12:00
2) 9.9.9.9/32 Added by PayneCarbon at UTC time: 2020-11-03 12:00
3) 4.3.2.1/32 Added by PayneCarbon at UTC time: 2020-11-03 12:00

Use 0 to remove them all, or list each you would like to remove.
Which ones would you like to remove [default=0]:
```
This way I would also support running with `--cleanup` to cleanup others automatically (and in that case I wouldn't add the users IP to the whitelist, performing just cleanup is possible).

2020-11-03 15:21 UTC, PolarPayne commented on kai/cli/addmyip.py
> +    assert len(response['SecurityGroups']) == 1
In general, do not use `assert`s for error checking as they are disabled when python is ran with `-O` or `PYTHONOPTIMIZE=1` and can lead to subtle bugs. Though in this case it's probably fine as the code will anyway fail on the next line if this fails, but even in that case the error message will be better without this.

2020-11-03 15:21 UTC, PolarPayne commented on kai/cli/addmyip.py
> +    return hostname
No real reason to have a variable here, right? 😅

2020-11-04 07:29 UTC, dzeih requested changes
Not much new to say after previous review but I stand by the comments left with it. Tool itself looks great!

2020-11-04 07:29 UTC, dzeih commented on kai/cli/addmyip.py
> +    return result.json()['ip']
Should we use http://checkip.amazonaws.com/ instead? Doesn't remove the hack but drops 3rd party from the middle.

2020-11-04 07:29 UTC, dzeih commented on kai/cli/addmyip.py
> +            remove_ip_ranges_added_by_tool(security_group_id)
I vote for nicknames within tag as in this example and automated default cleanup of previous matching tag ips IF ip not matching the new ip

2020-11-04 07:29 UTC, dzeih commented on kai/cli/addmyip.py
> +DEFAULT_SECURITY_GROUP_NAMES = {'kai-ms-ec2-access', 'kai-microservice-access'}
Get these from env? It's not too much of a trouble to store such values in bash_profile

2020-11-04 08:22 UTC, PolarPayne commented on kai/cli/addmyip.py
> +DEFAULT_SECURITY_GROUP_NAMES = {'kai-ms-ec2-access', 'kai-microservice-access'}
Sensible defaults probably work well enough here, but there should still be a way to override them (with environment variables or command line flags).

2020-11-04 12:49 UTC, latvanii commented on kai/cli/addmyip.py
> +    return result.json()['ip']
nice, didn't know about that

2020-11-05 12:38 UTC, dzeih approved these changes
👍

2020-11-05 12:38 UTC, dzeih commented on kai/cli/addmyip.py
> +                        f'Defaults to revoking all listed IP ranges. ')
End prompts with ':' to make it clear input is expected

2020-11-05 12:38 UTC, dzeih commented on kai/cli/addmyip.py
> +                permission_indices_to_remove = all_indices
Revoke all by default only if current computer name in added by description? DISCUSSED

2020-11-05 12:46 UTC, PolarPayne approved these changes

2020-11-05 12:46 UTC, PolarPayne commented on kai/cli/addmyip.py
> +                        f'Defaults to revoking all listed IP ranges. ')
As just discussed, end with `: ` (note the space in there).

2020-11-05 12:46 UTC, PolarPayne commented on kai/cli/addmyip.py
> +    add_my_ip(env='test', skip_cleanup=False, security_group=None)
This should still be removed.

2020-11-05 12:52 UTC, merged